# Generated by Django 4.2.1 on 2023-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_remove_post_category_postcategory_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
