# Generated by Django 4.2.1 on 2023-05-11 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0008_alter_post_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostUserFavourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="follow",
            field=models.ManyToManyField(
                through="content.PostUserFavourite", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
