# Generated by Django 4.2.1 on 2023-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_postuserfavourite_post_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                through="content.PostCategory",
                to="content.category",
                verbose_name="Категория",
            ),
        ),
    ]
