# Generated by Django 4.2.1 on 2023-05-17 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0013_remove_post_like_postuserlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                related_name="postslike",
                through="content.PostUserLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
