# Generated by Django 4.2.1 on 2023-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_alter_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="answer",
            field=models.BooleanField(default=False),
        ),
    ]
