# Generated by Django 4.2.1 on 2023-05-20 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_reply_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="time_in",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 20, 19, 33, 55, 455586, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
