# Generated by Django 4.2.1 on 2023-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_reply_time_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOTPEmailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.IntegerField(default=111111)),
            ],
        ),
    ]
