# Generated by Django 4.2.1 on 2023-05-22 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_customotpemailmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomOTPEmailModel",
        ),
    ]
