# Generated by Django 4.2.1 on 2023-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_emailaddresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddresses",
            name="otp",
            field=models.IntegerField(default="123456"),
        ),
    ]
