# Generated by Django 4.2.1 on 2023-05-22 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_emailaddresses_otp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
